### ISSUE TITLE
Corrupted Pdf File Exception 

### ISSUE THREAD

**Issue by ShadiKadri** [joaopegoraro/ComposePdfViewer#2]
when trying to render a corrupted pdf file it throws an exception and crashes the app,
it would be a good to have a fallback composable to view instead, or another way to display an error instead of an app crashing exception
the thrown exception :
    java.io.IOException: file not in PDF format or corrupted
        at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
        at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:171)
        at xyz.joaophp.pdfviewer.PdfViewerKt$loadPdf$3.invokeSuspend(PdfViewer.kt:209)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@29e3fb3, androidx.compose.runtime.BroadcastFrameClock@c3bd970, StandaloneCoroutine{Cancelling}@e5be4e9, AndroidUiDispatcher@215a56e]

**Comment by joaopegoraro** [comment]
fixed in #3 (by you btw, thanks!)
